config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  resources :posts
  get "api/posts", to: "posts#index", defaults: { format: :json }
  get "about", to: "pages#about"
  get 'home', to: "pages#home"

  # get '/signup' => 'users#new'
  # post '/users' => 'users#create'
  post '/my_network_admin' => 'sessions#create'
  get '/my_network_admin' => 'sessions#new'
  # post '/signin' => 'sessions#create'
  get '/my_network_admin_sign_out' => 'sessions#destroy'
  root "pages#home"

  # match '*unmatched', to: 'application#not_found_method', via: :all
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  
end

app/models/add_users.rb
class AddUsers < ActiveRecord::Migration[7.0]
  def change
    create_table :users do |t|
      t.column :email, :string
      t.column :password_hash, :string
      t.column :password_salt, :string
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    has_rich_text :body
    def to_param  # overridden
        title
    end
    validates :title, presence: true, length: {minimum: 5, maximum: 50}
    validates :body, presence: true, length: {minimum: 10, maximum: 15000}
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :password
    validates_confirmation_of :password
    validates :email, :presence => true, :uniqueness => true
    before_save :encrypt_password
  
    def encrypt_password
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
    end
  
    def self.authenticate(email, password)
      user = User.find_by "email = ?", email
      if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
        user
      else
        nil
      end
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    helper_method :current_user
    def not_found_method
      render file: Rails.public_path.join('404.html'), status: :not_found, layout: false
    end
    
    def current_user
        if session[:user_id]
            @current_user ||= User.find(session[:user_id])
        end
    end

    def authorize
        if !current_user
          flash[:notice] = "Please sign up before you can view the posts"
          redirect_to '/'
        end
    end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def internal_server_error
    render status: 500
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authorize, only: [:new, :edit]
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find_by(params[:title])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :image)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
      @user = User.authenticate(params[:email], params[:password])
      if @user
        flash[:notice] = "You've signed in."
        session[:user_id] = @user.id
        redirect_to "/posts"
      else
        flash[:alert] = "There was a problem signing in. Please try again."
        redirect_to "/my_network_admin"
      end
    end
  
    def destroy
      session[:user_id] = nil
      flash[:notice] = "You've signed out."
      redirect_to "/"
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You've successfully signed up!"
      session[:user_id] = @user.id
      redirect_to "/home"
    else
      flash[:alert] = "There was a problem signing up."
      redirect_to '/  '
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_navbar.html.erb
<%
=begin%>
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
<div class="container-fluid">
    <%= link_to "Rails Blog", root_path, class:'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to "Home", root_path, class:'nav-link active'%>
        </li>
        <li class="nav-item">
            <%= link_to "About", about_path, class:'nav-link'%>
        </li>
        <li class="nav-item">
            <%= link_to "Posts", posts_path, class:'nav-link'%>
        </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
            
            </li>
        </ul>
        </ul>
    </ul>
    </div>
</div>
</nav> 
<%
=end%>

<div>
    <nav class="navbar navbar-light bg-light">
        <%= link_to "CyberDavid", root_path, class:'navbar-brand'%>
        <%= link_to "Home", root_path, class:'nav-link active'%>
        <%= link_to "About", about_path, class:'nav-link'%>
        <%# <%= link_to "Support", "https://www.buymeacoffee.com/", target: "_blank" class:'nav-link'%>
        <%# link_to "GOOGLE", "http://www.google.com", target: "_blank", class: "btn btn-large btn-primary" %>
        <a href="https://www.buymeacoffee.com/", target='__blank' class='nav-link'> Support </a>
        <%= link_to "Posts", posts_path, class:'nav-link'%>
        <form class="form-inline">
            <div style="padding-left: 10px;">
            <% if current_user %>
                <%= link_to "Sign out", '/my_network_admin_sign_out',class:'btn btn-outline-success'%>
            <%end%>
                <%
=begin%>
 <% if current_user %>
                    <div class="text-success">
                        <%= current_user.email %> 
                    </div>
                    <%= link_to "Sign out", '/signout', class:'btn btn-outline-success' %>
                <% else %>
                    <div class="text-danger">
                        <%= "Not logged in" %>
                    </div>
                    <%= link_to "Sign up", 'signup', class:'btn btn-outline-success' %> | <%= link_to "Sign in", '/signin', class:'btn btn-outline-success' %>
                <% end %> 
<%
=end%>
            </div>
        </form>
    </nav>
    <% flash.each do |type, msg| %>
        <div class="alert alert-danger">
          <%= msg %>
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
      <%= render 'layouts/navbar' %>
      <main>
        <%= yield %>
      </main>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
<div class="container">
<body>

<div id="layout" class="pure-g">

    <div class="content pure-u-1 pure-u-md-3-4">
        <div>
            <div class="posts">
                <section class="post">
                        <h2 class="post-title">About me</h2>
                    <div class="post-description">
                        <div class="post-images pure-g">
                            <div class="pure-u-1 pure-u-md-1-2">
                                    <img alt="Photo of code"
                                         class="pure-img-responsive"
                                         src="https://cdn.pixabay.com/photo/2015/12/09/15/51/code-1084923__340.png">
                            <div class="pure-u-1 pure-u-md-1-2">

                            </div>
                        </div>
                    </div>
                        <p>
                            I am an ambitious person who is always learning anything related to tech. 
                        </p>
                        <p>
                         Currently my skillset includes web and software development, networking and penetration testing. 
                        </p>
                        <p>
                        In my spare time, and not not only. I like doing CTFs, building applications, playing around with network software 
                        </p>
                        <p>
                        and installing random linux distros just cuz I like it (I use arch btw). 
                        </p>
                        <p>
                        Feel free to get in touch with me about anything.
                        </p>
                    </div>
                </section>
            </div>

            <div class="footer">
                <div class="pure-menu pure-menu-horizontal">
                    <ul>
                        <li class="pure-menu-item"><a href="https://twitter.com/davidhayrapet" class="pure-menu-link" target="__blank">Twitter</a></li>
                        <li class="pure-menu-item"><a href="https://github.com/networkdavit" class="pure-menu-link" target="__blank">GitHub</a></li>
                        <li class="pure-menu-item"><a href="https://www.linkedin.com/in/davit-hayrapetyan-784a72210/" class="pure-menu-link" target="__blank">Linkedin</a></li>

                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</div>
</div>

app/views/pages/home.html.erb
<div class="container">
    <div class="container">
        <body>

        <div id="layout" class="pure-g">

            <div class="content pure-u-1 pure-u-md-3-4">
                <div>
                    <div class="posts">

                        <section class="post">
                                <h2 class="post-title">Welcome to CyberDavid</h2>
                            <div class="post-description">
                                <p>
                                Hi! I am David, welcome to my blog! Allow me introduct myself.
                                </p>
                                <p>
                                I am a software developer, cybersecurity consultant and CTF player.
                                </p>
                                <p>
                                In this blog you are going to find posts about programming, technologies 
                                </p>
                                <p>
                                cybersecurity and CTF walkthroughs from HackTheBox, TryHackme, etc. 
                                </p>
                            </div>
                        </section>
                    </div>
                    <div class="posts">
                        <hr>
                        <section class="post">
                            <header class="post-header">

                                <h2 class="post-title">Everything You Need to Know</h2>
                                <h2 class="post-title">Before Reading My Blog</h2>
                                    <div class="post-images pure-g">
                                        <div class="pure-u-1 pure-u-md-1-2">
                                        <img alt="Photo of setup"
                                        class="pure-img-responsive"
                                        src="https://cdn.pixabay.com/photo/2020/01/26/20/14/computer-4795762__340.jpg">
                                    </div>
                                <p class="post-meta">
                                </p>
                            </header>

                            <div class="post-description">
                                <p>
                                    This blog is dedicated to anything I do related to tech. You will find articles about
                                </p>
                                <p>
                                 programming technologies networking, CTF writeups, development tutorials and innovations.
                                </p>
                                <p>
                                 Thank you for visiting my blog!
                                </p>
                            </div>
                        </section>
                    </div>

                    <div class="footer">
                        <div class="pure-menu pure-menu-horizontal">
                            <ul>
                                <li class="pure-menu-item"><a href="https://twitter.com/davidhayrapet" class="pure-menu-link" target="__blank">Twitter</a></li>
                                <li class="pure-menu-item"><a href="https://github.com/networkdavit" class="pure-menu-link" target="__blank">GitHub</a></li>
                                <li class="pure-menu-item"><a href="https://www.linkedin.com/in/davit-hayrapetyan-784a72210/" class="pure-menu-link" target="__blank">Linkedin</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        </body>
    </div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <%= form.label :image %>
    <%= form.text_area :image %>
  </div>

  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %>
    <%= form.rich_text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>Posts</h1>
  
    <% if current_user  && current_user.admin  %>
      <%= link_to 'New Post', new_post_path %>
    <% end %>
    <table class="table">
      <thead>
        <tr>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= post.title %></td>
            <%
=begin%>
 <td><%= post.body %></td> 
<%
=end%>
            <td><img width="100px" height="50px" src="<%= (url_for(post.image)) %>"></td>
            <td><%= link_to 'Show', post %></td>
            <% if current_user && current_user.admin %>
              <td><%= link_to 'Edit', edit_post_path(post) %></td>
              <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <%end%>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<img width="100%" height="auto" src="<%= (url_for(@post.image)) %>">
<hr>
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
<hr>

<p>
  <%= @post.body %>
</p>

<% if current_user  && current_user.admin  %>%
  <%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', posts_path %>

app/views/users/new.html.erb
<h1> Sign up</h1>
<%= form_for @user do |f| %>
  <%= f.label "Email" %>
  <%= f.text_field :email %>
  <%= f.label "Password" %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Sign Up" %>
<% end %>